#############################################################################
# Makefile for building: ReceiptTracker
# Generated by qmake (3.1) (Qt 5.15.17)
# Project:  ../../ReceiptTracker.pro
# Template: app
# Command: /Users/andrew/Qt/5.15.17/ios/bin/qmake -o Makefile ../../ReceiptTracker.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk -miphoneos-version-min= -fobjc-nonfragile-abi -fobjc-legacy-dispatch -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk -miphoneos-version-min= -fobjc-nonfragile-abi -fobjc-legacy-dispatch -fPIC $(DEFINES)
INCPATH       = -I../../../ReceiptTracker -I. -I../../../../Qt/5.15.17/ios/mkspecs/common/uikit -I../../../../Qt/5.15.17/ios/mkspecs/macx-ios-clang
QMAKE         = /Users/andrew/Qt/5.15.17/ios/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/andrew/Qt/5.15.17/ios/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/andrew/Qt/5.15.17/ios/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ReceiptTracker1.0.0
DISTDIR = /Users/andrew/QtCreations/ReceiptTracker/build/Qt_5_15_17_ios-Debug/.tmp/ReceiptTracker1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk -miphoneos-version-min= -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS)    
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../../main.cpp 
OBJECTS       = main.o
DIST          = /Qt/5.15.17/ios/mkspecs/features/spec_pre.prf \
		/Qt/5.15.17/ios/mkspecs/qdevice.pri \
		/Qt/5.15.17/ios/mkspecs/features/device_config.prf \
		/Qt/5.15.17/ios/mkspecs/common/unix.conf \
		/Qt/5.15.17/ios/mkspecs/common/mac.conf \
		/Qt/5.15.17/ios/mkspecs/common/uikit.conf \
		/Qt/5.15.17/ios/mkspecs/common/ios.conf \
		/Qt/5.15.17/ios/mkspecs/common/sanitize.conf \
		/Qt/5.15.17/ios/mkspecs/common/gcc-base.conf \
		/Qt/5.15.17/ios/mkspecs/common/gcc-base-mac.conf \
		/Qt/5.15.17/ios/mkspecs/common/clang.conf \
		/Qt/5.15.17/ios/mkspecs/common/clang-mac.conf \
		/Qt/5.15.17/ios/mkspecs/common/uikit/clang.conf \
		/Qt/5.15.17/ios/mkspecs/common/uikit/qmake.conf \
		/Qt/5.15.17/ios/mkspecs/qconfig.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext__clip2tri.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext__clipper.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext__poly2tri.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_freetype.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_harfbuzz.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg12bits.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg16bits.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_libpng.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_pcre2.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_ext_qmapboxgl.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3danimation.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dextras.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3drender.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_charts.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_charts_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_core.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_gamepad.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_gui.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_help.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttracker.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttracker_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_location.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_macextras.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_network.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_networkauth.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_nfc.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdf.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdf_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_purchasing.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qml.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quick.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_repparser.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_script.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_script_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_scripttools.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_scxml.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_sql.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_svg.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_webview.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_xml.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_insighttrackerplugin.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_openglrenderer.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qgif.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qpdf.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Qt/5.15.17/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		/Qt/5.15.17/ios/mkspecs/features/qt_functions.prf \
		/Qt/5.15.17/ios/mkspecs/features/qt_config.prf \
		/Qt/5.15.17/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Qt/5.15.17/ios/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		/Qt/5.15.17/ios/mkspecs/features/exclusive_builds.prf \
		/Qt/5.15.17/ios/mkspecs/features/mac/sdk.prf \
		/Qt/5.15.17/ios/mkspecs/features/uikit/sdk.prf \
		/Qt/5.15.17/ios/mkspecs/features/toolchain.prf \
		/Qt/5.15.17/ios/mkspecs/features/mac/toolchain.prf \
		/Qt/5.15.17/ios/mkspecs/features/default_pre.prf \
		/Qt/5.15.17/ios/mkspecs/features/mac/default_pre.prf \
		/Qt/5.15.17/ios/mkspecs/features/uikit/default_pre.prf \
		/Qt/5.15.17/ios/mkspecs/features/resolve_config.prf \
		/Qt/5.15.17/ios/mkspecs/features/uikit/resolve_config.prf \
		/Qt/5.15.17/ios/mkspecs/features/default_post.prf \
		/Qt/5.15.17/ios/mkspecs/features/mac/default_post.prf \
		/Qt/5.15.17/ios/mkspecs/features/uikit/default_post.prf \
		/Qt/5.15.17/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Qt/5.15.17/ios/mkspecs/features/mac/objective_c.prf \
		../../../../ReceiptTracker.pro  ../../main.cpp
QMAKE_TARGET  = ReceiptTracker
DESTDIR       = 
TARGET        = ReceiptTracker

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = iphoneos
EXPORT_QMAKE_MAC_SDK_VERSION = 17.5
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/andrew/QtCreations/ReceiptTracker/build/Qt_5_15_17_ios-Debug/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/andrew/QtCreations/ReceiptTracker/ReceiptTracker.pro


include /Users/andrew/Qt/5.15.17/ios/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

ReceiptTracker:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../../ReceiptTracker.pro ../../../../Qt/5.15.17/ios/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.15.17/ios/mkspecs/qdevice.pri \
		../../../../Qt/5.15.17/ios/mkspecs/features/device_config.prf \
		../../../../Qt/5.15.17/ios/mkspecs/common/unix.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/mac.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/uikit.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/ios.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/sanitize.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/clang.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/uikit/clang.conf \
		../../../../Qt/5.15.17/ios/mkspecs/common/uikit/qmake.conf \
		../../../../Qt/5.15.17/ios/mkspecs/qconfig.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext__clip2tri.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext__clipper.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext__poly2tri.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg12bits.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg16bits.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_pcre2.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_qmapboxgl.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttracker.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdf.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_insighttrackerplugin.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_openglrenderer.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qpdf.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		../../../../Qt/5.15.17/ios/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/qt_config.prf \
		../../../../Qt/5.15.17/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../../../Qt/5.15.17/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.15.17/ios/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/uikit/sdk.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/toolchain.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/default_pre.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/uikit/default_pre.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/uikit/resolve_config.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/default_post.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/uikit/default_post.prf \
		../../../../Qt/5.15.17/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../../../Qt/5.15.17/ios/mkspecs/features/mac/objective_c.prf \
		../../ReceiptTracker.pro
	$(QMAKE) -o Makefile ../../ReceiptTracker.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
../../../../Qt/5.15.17/ios/mkspecs/features/spec_pre.prf:
../../../../Qt/5.15.17/ios/mkspecs/qdevice.pri:
../../../../Qt/5.15.17/ios/mkspecs/features/device_config.prf:
../../../../Qt/5.15.17/ios/mkspecs/common/unix.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/mac.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/uikit.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/ios.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/sanitize.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/gcc-base.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/clang.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/clang-mac.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/uikit/clang.conf:
../../../../Qt/5.15.17/ios/mkspecs/common/uikit/qmake.conf:
../../../../Qt/5.15.17/ios/mkspecs/qconfig.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext__clip2tri.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext__clipper.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext__poly2tri.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_freetype.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_harfbuzz.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg12bits.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libjpeg16bits.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_libpng.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_pcre2.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_ext_qmapboxgl.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttracker.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttracker_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttrackerqml.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdf.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdf_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_insighttrackerplugin.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_openglrenderer.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qgif.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qicns.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qico.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qios.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qpdf.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtga.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../../../../Qt/5.15.17/ios/mkspecs/modules/qt_plugin_scene2d.pri:
../../../../Qt/5.15.17/ios/mkspecs/features/qt_functions.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/qt_config.prf:
../../../../Qt/5.15.17/ios/mkspecs/macx-ios-clang/qmake.conf:
../../../../Qt/5.15.17/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.15.17/ios/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/uikit/sdk.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/toolchain.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/mac/toolchain.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/default_pre.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/uikit/default_pre.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/resolve_config.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/uikit/resolve_config.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/default_post.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/uikit/default_post.prf:
../../../../Qt/5.15.17/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../../../Qt/5.15.17/ios/mkspecs/features/mac/objective_c.prf:
../../ReceiptTracker.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ../../ReceiptTracker.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ReceiptTracker

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug

compiler_clean: 

####### Compile

main.o: ../../main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../../main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

